### ISSUE TITLE
Nothing to see on website after installing

### ISSUE THREAD

**Issue by TheGunter24** [splewis/get5-web#121]
hello,
i am did follow the steps to install.
(did change folder get5-web to get5)+(am using debian 8)
when i finished installing i did not find the venv folder inside get5, so i copied it in there.

after all i dont see any homepage (and tbh, i am woundering because no .php oder .html is included) 

can i get some info (or copy from working one) on what could be wrong ? or i need to do ? 

thx

**Comment by TandelK** [comment]
venv folder is not there by default it gets created with command of virtualenv venv.

https://github.com/splewis/get5-web/blob/master/INSTALL.md

Please go through Step 5 from this guide. Make sure you have installed Python 2.7 and also the reason it might be not showing properly is because of wsgi module.

**Comment by TheGunter24** [comment]
i had python installed from command line not manually from their website, which i did now.
but i get this error now:

root@tg24server:/var/www/html/get5# virtualenv venv
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in venv/bin/python2
Not overwriting existing python script venv/bin/python (you must use venv/bin/py                                                                                                                                                             thon2)
Installing setuptools, pip...
  Complete output from command /var/www/html/get5/venv/bin/python2 -c "import sy                                                                                                                                                             s, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py"                                                                                                                                                             , line 73, in <module>
  File "/usr/share/python-wheels/pip-1.5.6-py2.py3-none-any.whl/pip/util.py", li                                                                                                                                                             ne 20, in <module>
  File "/var/www/html/get5/venv/lib/python-wheels/distlib-0.1.9-py2.py3-none-any                                                                                                                                                             .whl/distlib/version.py", line 14, in <module>
  File "/var/www/html/get5/venv/lib/python-wheels/distlib-0.1.9-py2.py3-none-any                                                                                                                                                             .whl/distlib/compat.py", line 31, in <module>
ImportError: cannot import name HTTPSHandler
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2378, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 830, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 1032, in create_envi                                                                                                                                                             ronment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 975, in install_whee                                                                                                                                                             l
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 917, in call_subproc                                                                                                                                                             ess
    % (cmd_desc, proc.returncode))
OSError: Command /var/www/html/get5/venv/bin/python2 -c "import sys, pip; sys...                                                                                                                                                             d\"] + sys.argv[1:]))" setuptools pip failed with error code 1

**Comment by Technoblazed** [comment]
Reinstall python

**Comment by TheGunter24** [comment]
ill try :)

**Comment by TheGunter24** [comment]
root@tg24server:/etc/Python-2.7.13# make
running build
running build_ext
INFO: Can't locate Tcl/Tk libs and/or headers

Python build finished, but the necessary bits to build these modules were not fo                                                                                                                                                             und:
_bsddb             _curses            _curses_panel
_sqlite3           _ssl               _tkinter
bsddb185           bz2                dbm
dl                 gdbm               imageop
readline           sunaudiodev
To find the necessary bits, look in setup.py in detect_modules() for the module'                                                                                                                                                             s name.

**Comment by TandelK** [comment]
If you dont have any of the things installed on the system i would really recommend reinstalling complete OS instead of going to correct this errors. Will take lot of time. Just a suggestion its not a solution and by default Python2.7 is preinstalled in Ubuntu and Debian. You dont need to do it again.

**Comment by Technoblazed** [comment]
If you'd provide some more system information like your distribution, it'd help. Currently all we have from you is that it isn't working.

**Comment by TheGunter24** [comment]
root@tg24server:~# python --version
Python 2.7.13
root@tg24server:~# python3 --version
Python 3.4.2

but i only installed python 2, version 4 gets installed when running the commands in # 2 from install guide

**Comment by TheGunter24** [comment]
3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 GNU/Linux'
is what i am running

**Comment by TheGunter24** [comment]
can i use python 3 instead of 2 ? when i try to install virtualenv it will automaticly include python 3 again

**Comment by TheGunter24** [comment]
installed packages: https://pastebin.com/aEHXhkCs

**Comment by Technoblazed** [comment]
I made the install guide for people that are super lazy and couldn't figure stuff out themselves. If you're using custom versions etc. you're just gonna have to google it as best you can.

https://github.com/splewis/get5-web#installation

**Comment by TheGunter24** [comment]
U can Close this then 
Thx

**Comment by TheGunter24** [comment]
U can Close this then 
Thx

**Comment by TandelK** [comment]
@TheGunter24 contact me on Discord with TandelK#7676 or at Steam at gg.gg/TandelK
