### ISSUE TITLE
Error after installing 

### ISSUE THREAD

**Issue by Mrciller** [splewis/get5-web#126]
I never had it bevor but this time this happend

[Fri Jan 18 15:03:50.991585 2019] [wsgi:warn] [pid 27879] mod_wsgi: Compiled for Python/2.7.11.
[Fri Jan 18 15:03:50.991688 2019] [wsgi:warn] [pid 27879] mod_wsgi: Runtime using Python/2.7.12.
[Fri Jan 18 15:03:50.999004 2019] [mpm_prefork:notice] [pid 27879] AH00163: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Fri Jan 18 15:03:50.999067 2019] [core:notice] [pid 27879] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 18 15:03:54.668901 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895] mod_wsgi (pid=27883): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Fri Jan 18 15:03:54.668970 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895] mod_wsgi (pid=27883): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Fri Jan 18 15:03:54.669023 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895] Traceback (most recent call last):
[Fri Jan 18 15:03:54.669058 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Fri Jan 18 15:03:54.669185 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     from get5 import app as application
[Fri Jan 18 15:03:54.669196 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/var/www/get5-web/get5/__init__.py", line 59, in <module>
[Fri Jan 18 15:03:54.669321 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     from models import User, Team, GameServer, Match, MapStats, PlayerStats  # noqa: E402
[Fri Jan 18 15:03:54.669333 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/var/www/get5-web/get5/models.py", line 7, in <module>
[Fri Jan 18 15:03:54.669556 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     import requests
[Fri Jan 18 15:03:54.669573 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/var/www/get5-web/venv/lib/python2.7/site-packages/requests/__init__.py", line 53, in <module>
[Fri Jan 18 15:03:54.669655 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     from .packages.urllib3.contrib import pyopenssl
[Fri Jan 18 15:03:54.669669 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/var/www/get5-web/venv/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 54, in <module>
[Fri Jan 18 15:03:54.669835 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     import OpenSSL.SSL
[Fri Jan 18 15:03:54.669850 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[Fri Jan 18 15:03:54.669900 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     from OpenSSL import rand, crypto, SSL
[Fri Jan 18 15:03:54.669918 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
[Fri Jan 18 15:03:54.669983 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     from OpenSSL._util import (
[Fri Jan 18 15:03:54.669992 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 4, in <module>
[Fri Jan 18 15:03:54.670025 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     binding = Binding()
[Fri Jan 18 15:03:54.670034 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
[Fri Jan 18 15:03:54.670108 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     self._ensure_ffi_initialized()
[Fri Jan 18 15:03:54.670118 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
[Fri Jan 18 15:03:54.670228 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     libraries=libraries,
[Fri Jan 18 15:03:54.670240 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 80, in build_ffi
[Fri Jan 18 15:03:54.670332 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     extra_link_args=extra_link_args,
[Fri Jan 18 15:03:54.670344 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cffi/api.py", line 340, in verify
[Fri Jan 18 15:03:54.670517 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     lib = self.verifier.load_library()
[Fri Jan 18 15:03:54.670537 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 75, in load_library
[Fri Jan 18 15:03:54.670638 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     return self._load_library()
[Fri Jan 18 15:03:54.670648 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cffi/verifier.py", line 151, in _load_library
[Fri Jan 18 15:03:54.670665 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     return self._vengine.load_library()
[Fri Jan 18 15:03:54.670673 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]   File "/usr/lib/python2.7/dist-packages/cffi/vengine_cpy.py", line 149, in load_library
[Fri Jan 18 15:03:54.670941 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895]     raise ffiplatform.VerificationError(error)
[Fri Jan 18 15:03:54.670991 2019] [wsgi:error] [pid 27883] [client 192.164.8.103:56895] VerificationError: importing '/usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so': /usr/lib/python2.7/dist-packages/cryptography/_Cryptography_cffi_813c10e0x7adb75f8.x86_64-linux-gnu.so: symbol SSLv2_client_method, version OPENSSL_1.0.0 not defined in file libssl.so.1.0.0 with link time reference

**Comment by Technoblazed** [comment]
Recreate the get5.wsgi script, you've done something wrong there.

**Comment by Mrciller** [comment]
my get5.wshi looks like this



#!/usr/bin/python

activate_this = '/var/www/get5-web/venv/bin/activate_this.py'
execfile(activate_this, dict(__file__=activate_this))

import sys
import logging
logging.basicConfig(stream=sys.stderr)

folder = "/var/www/get5-web"
if not folder in sys.path:
    sys.path.insert(0, folder)
sys.path.insert(0,"")

from get5 import app as application
import get5
get5.register_blueprints()

**Comment by Mrciller** [comment]
and i use Debian 9 i hope that is no problem

**Comment by Mrciller** [comment]
eroor update after installing it on another debian 9 server i get this error



[Fri Jan 18 15:24:19.191344 2019] [wsgi:warn] [pid 1381] mod_wsgi: Compiled for Python/3.5.1+.
[Fri Jan 18 15:24:19.191412 2019] [wsgi:warn] [pid 1381] mod_wsgi: Runtime using Python/3.5.2.
[Fri Jan 18 15:24:19.197013 2019] [mpm_prefork:notice] [pid 1381] AH00163: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/3.5.2 configured -- resuming normal operations
[Fri Jan 18 15:24:19.197069 2019] [core:notice] [pid 1381] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jan 18 15:24:48.976914 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122] mod_wsgi (pid=1385): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Fri Jan 18 15:24:48.977007 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122] mod_wsgi (pid=1385): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Fri Jan 18 15:24:48.977341 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122] Traceback (most recent call last):
[Fri Jan 18 15:24:48.977362 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122]   File "/var/www/get5-web/get5.wsgi", line 4, in <module>
[Fri Jan 18 15:24:48.977365 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122]     execfile(activate_this, dict(__file__=activate_this))
[Fri Jan 18 15:24:48.977381 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122] NameError: name 'execfile' is not defined

**Comment by TandelK** [comment]
> [Fri Jan 18 15:24:48.976914 2019] [wsgi:error] [pid 1385] [client 192.164.8.103:57122] mod_wsgi (pid=1385): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.

If the issue has been resolved would recommend closing it, BTW i see that your wsgi module of apache is not working and thats the reason whole issue is there.
