### ISSUE TITLE
 'ascii' codec can't encode character u'\xa7' in position 11

### ISSUE THREAD

**Issue by SGTshan** [splewis/get5-web#132]
Everytime I want to add a server it gives me that error. My error log shows this:

`
[2019-02-10 18:17:19,873] {/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py:1423} ERROR - Exception on /server/create [POST]
Traceback (most recent call last):
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/get5-web/get5/server.py", line 59, in server_create
    if mock or util.check_server_connection(server):
  File "/var/www/get5-web/get5/util.py", line 32, in check_server_connection
    server.ip_string, server.port, server.rcon_password, 'status')
  File "/var/www/get5-web/get5/util.py", line 88, in send_rcon_command
    with RCON((host, port), rcon_password, timeout=timeout) as rcon:
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/valve/source/rcon.py", line 126, in __enter__
    self.authenticate(self.password)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/valve/source/rcon.py", line 249, in authenticate
    request = self.request(Message.SERVERDATA_AUTH, unicode(password))
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/valve/source/rcon.py", line 166, in request
    self._socket.sendall(request.encode())
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/valve/source/rcon.py", line 78, in encode
    self.body.encode("ascii") + b"\x00\x00")
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/valve/source/rcon.py", line 67, in size
    return struct.calcsize(b"<ii") + len(self.body.encode("ascii")) + 2
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 11: ordinal not in range(128)
[2019-02-10 18:17:19,875] {/var/www/get5-web/get5/__init__.py:155} ERROR - 'ascii' codec can't encode character u'\xa7' in position 11: ordinal not in range(128)
`

Can someone help me ?

**Comment by SGTshan** [comment]
The RCON password of your gameserver should not have any special chars. I think this could also be fixed by changing the encoding to utf8, not ascii.

**Comment by splewis** [comment]
The encodings for all strings should likely all be changed. Anyone is free to send a pull request with the changes.
