### ISSUE TITLE
plz help me error db upgrade

### ISSUE THREAD

**Issue by suspectykt** [splewis/get5-web#149]
(venv) root@localhost:/var/www/get5-web# ./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 60, in <module>
    from models import User, Team, GameServer, Match, MapStats, PlayerStats  # noqa: E402
  File "/var/www/get5-web/get5/models.py", line 29
    rv.steam_id = steam_id
    ^
IndentationError: unexpected indent

**Comment by suspectykt** [comment]
Problem was with spaces in the code
