### ISSUE TITLE
missing player stats from match if steam nickname contain any utf character

### ISSUE THREAD

**Issue by gouyeh** [splewis/get5-web#159]
**get5.log**
`[2019-07-06 00:49:58,692] {/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py:1423} ERROR - Exception on /match/785/map/0/player/76561197971168702/update [POST]
Traceback (most recent call last):
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask_limiter/extension.py", line 442, in __inner
    return obj(*a, **k)
  File "/var/www/get5-web/get5/api.py", line 199, in match_map_update_player
    db.session.commit()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 801, in commit
    self.transaction.commit()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 392, in commit
    self._prepare_impl()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 372, in _prepare_impl
    self.session.flush()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2019, in flush
    self._flush(objects)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2101, in _flush
    flush_context.execute()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x94' for column `get5`.`player_stats`.`name` at row 1") [SQL: u'INSERT INTO player_stats (match_id, map_id, team_id, stea$
[2019-07-06 00:49:58,693] {/var/www/get5-web/get5/__init__.py:155} ERROR - (_mysql_exceptions.OperationalError) (1366, "Incorrect string value: '\\xF0\\x9F\\x92\\x94' for column `get5`.`pl$
[2019-07-06 01:40:09,512] {/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py:1423} ERROR - Exception on /match/785/map/1/player/76561197971168702/update [POST]`

**Comment by PhlexPlexico** [comment]
https://github.com/splewis/get5-web/issues/101

You need to adjust some database values as mentioned there.
