### ISSUE TITLE
./manager.py db upgrade issue 

### ISSUE THREAD

**Issue by drkamine** [splewis/get5-web#165]
./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 26, in <module>
    import steamid
  File "/var/www/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id

**Comment by andrel0** [comment]
Hello, could you tell me how this error can be solved? I have been trying to find the solution to this message for 1 week. Did you succeed in solving this problem? Thanks! very much

**Comment by splewis** [comment]
Did you install the dependencies? Are you running in a virtualenv like the readme suggests?

**Comment by andrel0** [comment]
Hello splewis , yes / yes. Run it on Centos 7, install all dependencies and libraries associated and similar to Ubuntu. Run it in virtualenv with python 2.7.5 and 3.6.

**Comment by itsdan25** [comment]
(venv) root@comp2:/var/www/html/get5-web# ./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/html/get5-web/get5/__init__.py", line 26, in <module>
    import steamid
  File "/var/www/html/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id


___ 

Debian 10
