### ISSUE TITLE
./manager.py db upgrade

### ISSUE THREAD

**Issue by andrel0** [splewis/get5-web#181]
**Hello! ,** 

```
I have centos7 / mariadb mysql / python 2.7 and pip 19.3.1. Unfortunately, the name of the BD is not only called "get5" but when you have cpanel it generates an alias before. Example:
user_get5.
```

Any suggestions for this error ( I am having problems during the process ) :

# ./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/home/tournament/public_html/play/plataforma-mm/get5/__init__.py", line 29, in <module>
    from flask import (Flask, render_template, flash, jsonify,
  File "/home/tournament/public_html/play/plataforma-mm/venv/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/home/tournament/public_html/play/plataforma-mm/venv/lib/python2.7/site-packages/flask/app.py", line 20, in <module>
    from werkzeug.routing import Map, Rule, RequestRedirect, BuildError
  File "/home/tournament/public_html/play/plataforma-mm/venv/lib/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables

**Comment by SirNiggo** [comment]
Did you set your connection string for the get5-web config according to the user_get5 database name?

**Comment by andrel0** [comment]
Hi Nico, thanks for answering. It is correct, set the username / password and address of the BD.
