### ISSUE TITLE
./manager.py db upgrade

### ISSUE THREAD

**Issue by realRapSi** [splewis/get5-web#182]
This is the error I get if I type the command ./manager.py db upgrade into the terminal.

Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/var/www/get5-web/get5/__init__.py", line 26, in <module>
    import steamid
  File "/var/www/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id

Before executing this above I also had this error while installing the requirements.txt file:

ERROR: Command errored out with exit status 1:
     command: /home/pi/miniconda3/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a_3hhopb/enum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a_3hhopb/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-a_3hhopb/enum/pip-egg-info
         cwd: /tmp/pip-install-a_3hhopb/enum/
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/miniconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg/setuptools/__init__.py", line 11, in <module>
      File "/home/pi/miniconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg/setuptools/extension.py", line 8, in <module>
      File "/home/pi/miniconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg/setuptools/dist.py", line 16, in <module>
      File "/home/pi/miniconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg/setuptools/depends.py", line 6, in <module>
      File "/home/pi/miniconda3/lib/python3.4/site-packages/setuptools-18.1-py3.4.egg/setuptools/compat.py", line 45, in <module>
      File "/home/pi/miniconda3/lib/python3.4/http/client.py", line 69, in <module>
        import email.parser
      File "/home/pi/miniconda3/lib/python3.4/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser, BytesFeedParser
      File "/home/pi/miniconda3/lib/python3.4/email/feedparser.py", line 27, in <module>
        from email import message
      File "/home/pi/miniconda3/lib/python3.4/email/message.py", line 16, in <module>
        from email import utils
      File "/home/pi/miniconda3/lib/python3.4/email/utils.py", line 29, in <module>
        import socket
      File "/home/pi/miniconda3/lib/python3.4/socket.py", line 53, in <module>
        from enum import IntEnum
    ImportError: cannot import name 'IntEnum'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can somebody please help me with this :)

**Comment by splewis** [comment]
I would not recommend trying to use anything other than python2.7 for this.
