### ISSUE TITLE
Install 

### ISSUE THREAD

**Issue by xPatrykPlayX** [splewis/get5-web#192]
ERROR: Command errored out with exit status 1:
     command: /var/www/get5-web/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bsrt66ew/enum/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bsrt66ew/enum/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bsrt66ew/enum/pip-egg-info
         cwd: /tmp/pip-install-bsrt66ew/enum/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/get5-web/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 6, in <module>
        import distutils.core
      File "/usr/lib/python3.8/distutils/core.py", line 16, in <module>
        from distutils.dist import Distribution
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "/var/www/get5-web/venv/lib/python3.8/site-packages/_virtualenv.py", line 74, in exec_module
        old(module)
      File "/usr/lib/python3.8/distutils/dist.py", line 9, in <module>
        import re
      File "/usr/lib/python3.8/re.py", line 145, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by GiaNTizmO** [comment]
Hello! Please, try use this fix from stackoverflow:
https://stackoverflow.com/a/45716067

**Comment by merhawitokbay123-design** [comment]
Hallo
