### ISSUE TITLE
create a team page doesn't work

### ISSUE THREAD

**Issue by csgentr** [splewis/get5-web#35]
it was working very well but suddenly it's started to give me this error when I click create a team page.

Sorry, unexpected error: 'get5.team.TeamForm object' has no attribute 'tag'

and this is logs history..

`UndefinedError: 'get5.team.TeamForm object' has no attribute 'tag'
[2016-12-12 13:30:52,981] {/var/www/get5-web/get5/__init__.py:150} ERROR - 'get5.team.TeamForm object' has no attribute 'tag'
[2016-12-12 14:29:32,307] {/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py:1423} ERROR - Exception on /team/create [GET]
Traceback (most recent call last):
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/get5-web/get5/team.py", line 92, in team_create
    edit=False, is_admin=g.user.admin)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/get5-web/get5/templates/team_create.html", line 3, in top-level template code
    {% extends "layout.html" %}
  File "/var/www/get5-web/get5/templates/layout.html", line 53, in top-level template code
    {% block content %}
  File "/var/www/get5-web/get5/templates/team_create.html", line 22, in block "content"
    {{ form.tag.label(class="col-sm-2 control-label") }}
  File "/var/www/get5-web/venv/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
    return getattr(obj, attribute)
UndefinedError: 'get5.team.TeamForm object' has no attribute 'tag'
[2016-12-12 14:29:32,308] {/var/www/get5-web/get5/__init__.py:150} ERROR - 'get5.team.TeamForm object' has no attribute 'tag'
`

**Comment by Technoblazed** [comment]
You've updated your webpage to the latest version, but haven't run 
```./manager db upgrade```
