### ISSUE TITLE
ImportError: No module named valve.steam.id

### ISSUE THREAD

**Issue by garycrj** [splewis/get5-web#56]
I have this problem when i run the: ./manager.py db upgrade

[root@192 get5-web]# ./manager.py db upgrade
Traceback (most recent call last):
  File "./manager.py", line 3, in <module>
    import get5
  File "/root/get5-web/get5/__init__.py", line 26, in <module>
    import steamid
  File "/root/get5-web/get5/steamid.py", line 1, in <module>
    from valve.steam.id import SteamID, SteamIDError
ImportError: No module named valve.steam.id

**Comment by Technoblazed** [comment]
Please read all of the installation instructions. You haven't run pip install to install the dependencies

**Comment by garycrj** [comment]
Thank's, now i have this problem:
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by Technoblazed** [comment]
So check your apache or nginx error logs

**Comment by garycrj** [comment]
[Thu Jun 29 00:20:37.854322 2017] [:error] [pid 26134] [client 192.168.1.3:63655] mod_wsgi (pid=26134): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Thu Jun 29 00:20:37.854399 2017] [:error] [pid 26134] [client 192.168.1.3:63655] mod_wsgi (pid=26134): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Thu Jun 29 00:20:37.854455 2017] [:error] [pid 26134] [client 192.168.1.3:63655] Traceback (most recent call last):
[Thu Jun 29 00:20:37.854493 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Thu Jun 29 00:20:37.854550 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     from get5 import app as application
[Thu Jun 29 00:20:37.854572 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/var/www/get5-web/get5/__init__.py", line 68, in <module>
[Thu Jun 29 00:20:37.854609 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     app.config['LOG_PATH'], when='midnight')
[Thu Jun 29 00:20:37.854630 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/usr/lib64/python2.7/logging/handlers.py", line 169, in __init__
[Thu Jun 29 00:20:37.854668 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Thu Jun 29 00:20:37.854689 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
[Thu Jun 29 00:20:37.854721 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Thu Jun 29 00:20:37.854741 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
[Thu Jun 29 00:20:37.854774 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     StreamHandler.__init__(self, self._open())
[Thu Jun 29 00:20:37.854793 2017] [:error] [pid 26134] [client 192.168.1.3:63655]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
[Thu Jun 29 00:20:37.854825 2017] [:error] [pid 26134] [client 192.168.1.3:63655]     stream = open(self.baseFilename, self.mode)
[Thu Jun 29 00:20:37.854866 2017] [:error] [pid 26134] [client 192.168.1.3:63655] IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log'
[Thu Jun 29 00:20:37.923760 2017] [:error] [pid 26133] [client 192.168.1.3:63656] mod_wsgi (pid=26133): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module., referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.923831 2017] [:error] [pid 26133] [client 192.168.1.3:63656] mod_wsgi (pid=26133): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'., referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.923911 2017] [:error] [pid 26133] [client 192.168.1.3:63656] Traceback (most recent call last):, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.923970 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924054 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     from get5 import app as application, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924129 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/var/www/get5-web/get5/__init__.py", line 68, in <module>, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924209 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     app.config['LOG_PATH'], when='midnight'), referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924245 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/usr/lib64/python2.7/logging/handlers.py", line 169, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924309 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay), referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924341 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924423 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     logging.FileHandler.__init__(self, filename, mode, encoding, delay), referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924457 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924514 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     StreamHandler.__init__(self, self._open()), referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924583 2017] [:error] [pid 26133] [client 192.168.1.3:63656]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open, referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924625 2017] [:error] [pid 26133] [client 192.168.1.3:63656]     stream = open(self.baseFilename, self.mode), referer: http://192.168.1.5/
[Thu Jun 29 00:20:37.924667 2017] [:error] [pid 26133] [client 192.168.1.3:63656] IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log', referer: http://192.168.1.5/

**Comment by splewis** [comment]
> IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log', referer: http://192.168.1.5/

The user the server is running as doesn't have permission to write that to file. It should.

**Comment by garycrj** [comment]
Assign permissions and same error

**Comment by garycrj** [comment]
> [Thu Jun 29 01:17:07.863701 2017] [:error] [pid 5676] [client 192.168.1.3:64949] mod_wsgi (pid=5676): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Thu Jun 29 01:17:07.863735 2017] [:error] [pid 5676] [client 192.168.1.3:64949] mod_wsgi (pid=5676): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Thu Jun 29 01:17:07.863758 2017] [:error] [pid 5676] [client 192.168.1.3:64949] Traceback (most recent call last):
[Thu Jun 29 01:17:07.863782 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Thu Jun 29 01:17:07.863837 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     from get5 import app as application
[Thu Jun 29 01:17:07.863847 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/var/www/get5-web/get5/__init__.py", line 68, in <module>
[Thu Jun 29 01:17:07.863948 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     app.config['LOG_PATH'], when='midnight')
[Thu Jun 29 01:17:07.863961 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/usr/lib64/python2.7/logging/handlers.py", line 169, in __init__
[Thu Jun 29 01:17:07.864191 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay)
[Thu Jun 29 01:17:07.864201 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__
[Thu Jun 29 01:17:07.864215 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     logging.FileHandler.__init__(self, filename, mode, encoding, delay)
[Thu Jun 29 01:17:07.864222 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
[Thu Jun 29 01:17:07.864508 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     StreamHandler.__init__(self, self._open())
[Thu Jun 29 01:17:07.864519 2017] [:error] [pid 5676] [client 192.168.1.3:64949]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
[Thu Jun 29 01:17:07.864533 2017] [:error] [pid 5676] [client 192.168.1.3:64949]     stream = open(self.baseFilename, self.mode)
[Thu Jun 29 01:17:07.864558 2017] [:error] [pid 5676] [client 192.168.1.3:64949] IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log'
[Thu Jun 29 01:17:07.934668 2017] [:error] [pid 1020] [client 192.168.1.3:64948] mod_wsgi (pid=1020): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module., referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934714 2017] [:error] [pid 1020] [client 192.168.1.3:64948] mod_wsgi (pid=1020): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'., referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934751 2017] [:error] [pid 1020] [client 192.168.1.3:64948] Traceback (most recent call last):, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934780 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934823 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     from get5 import app as application, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934841 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/var/www/get5-web/get5/__init__.py", line 68, in <module>, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934883 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     app.config['LOG_PATH'], when='midnight'), referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934907 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/usr/lib64/python2.7/logging/handlers.py", line 169, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934937 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay), referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934953 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/usr/lib64/python2.7/logging/handlers.py", line 64, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.934997 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     logging.FileHandler.__init__(self, filename, mode, encoding, delay), referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.935014 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.935040 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     StreamHandler.__init__(self, self._open()), referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.935055 2017] [:error] [pid 1020] [client 192.168.1.3:64948]   File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open, referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.935080 2017] [:error] [pid 1020] [client 192.168.1.3:64948]     stream = open(self.baseFilename, self.mode), referer: http://192.168.1.5/
[Thu Jun 29 01:17:07.935112 2017] [:error] [pid 1020] [client 192.168.1.3:64948] IOError: [Errno 13] Permission denied: '/var/www/get5-web/logs/get5.log', referer: http://192.168.1.5/

**Comment by garycrj** [comment]
Can help me how assign permissions to write that to file?

**Comment by keeradfun** [comment]
try this out
chown -R username directory
chmod -R 777 directory

**Comment by Technoblazed** [comment]
777 on a directory is a terrible idea

**Comment by keeradfun** [comment]
Technoblazed so what should be used instead.

**Comment by Technoblazed** [comment]
Well 660 is the normal safe bet, then add +x to what you need

**Comment by Technoblazed** [comment]
His issue doesn't even need those, he just needs to chown the folder to whichever group the python wsgi is running on.

**Comment by splewis** [comment]
There's been no activity here, so I'm closing this.
