### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by SHaenk** [splewis/get5-web#74]
Hey!
when i am trying to enter into the site i get a 500 internal server error,
the httpd log shows me this:

```
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229] mod_wsgi (pid=5469): Target WSGI script '/var/www/get5-web/get5.wsgi' cannot be loaded as Python module.
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229] mod_wsgi (pid=5469): Exception occurred processing WSGI script '/var/www/get5-web/get5.wsgi'.
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229] Traceback (most recent call last):
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]   File "/var/www/get5-web/get5.wsgi", line 15, in <module>
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]     from get5 import app as application
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]   File "/var/www/get5-web/get5/__init__.py", line 26, in <module>
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]     import steamid
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]   File "/var/www/get5-web/get5/steamid.py", line 1, in <module>
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229]     from valve.steam.id import SteamID, SteamIDError
[Mon Dec 18 18:57:27 2017] [error] [client 5.102.254.229] ImportError: No module named valve.steam.id
```

I installed all by the guide.
I have centos 6.5

Thanks!

**Comment by Technoblazed** [comment]
Your requirements installation failed. This issue already exists in many other places: https://github.com/splewis/get5-web/issues/34 https://github.com/splewis/get5-web/issues/43 https://github.com/splewis/get5-web/issues/59 https://github.com/splewis/get5-web/issues/68 https://github.com/splewis/get5-web/issues/73
