### ISSUE TITLE
Sorry, you don't have access to this webpanel or 403

### ISSUE THREAD

**Issue by supaflybanzai** [splewis/get5-web#96]
hi,
what i doing wrong ?

##### You must change these before running
SQLALCHEMY_DATABASE_URI = 'mysql://get5:dbpass@localhost/get5'  # Sqlalchemy database connection info
STEAM_API_KEY = 'keyfromsteamapi'  # See https://steamcommunity.com/dev/apikey
SECRET_KEY = 'secret'  # Secret key used for flask cookies

import os

location = os.path.realpath(os.path.join(os.getcwd(), os.path.dirname(__file__), '..', 'logs'))
LOG_PATH = os.path.join(location, 'get5.log')

DEBUG = False
TESTING = False

SQLALCHEMY_TRACK_MODIFICATIONS = False
USER_MAX_SERVERS = 10  # Max servers a user can create
USER_MAX_TEAMS = 100  # Max teams a user can create
USER_MAX_MATCHES = 1000  # Max matches a user can create
DEFAULT_PAGE = '/matches'
ADMINS_ACCESS_ALL_MATCHES = False  # Whether admins can always access any match admin panel
CREATE_MATCH_TITLE_TEXT = False # Whether settings for "match title text" and "team text" appear on "create a match page"

MAPLIST = [
    'de_cache',
    'de_cbble',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
    'de_dust2',
    'de_season',
]

DEFAULT_MAPLIST = [
    'de_cache',
    'de_cbble',
    'de_inferno',
    'de_mirage',
    'de_nuke',
    'de_overpass',
    'de_train',
]

WHITELISTED_IDS = ["steamID64"]
ADMIN_IDS = ["steamID64"]

when i try open website i have 
403 forbidden

or when i delete ADMIN_IDS

WHITELISTED_IDS = ["steamID64"]
ADMIN_IDS = []
then
Sorry, you don't have access to this webpanel

when i delete both
WHITELISTED_IDS = []
ADMIN_IDS = []
then 403 forbidden

can somebody help me ?

**Comment by supaflybanzai** [comment]
rlly ? nobody cant help me ?

**Comment by supaflybanzai** [comment]
logs:

[2018-04-25 11:52:58,115] {/var/www/get5-web/get5/models.py:30} INFO - Creating user for 7656119813066****
[2018-04-25 11:52:58,370] {/usr/local/lib/python2.7/dist-packages/flask/app.py:1423} ERROR - Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_openid.py", line 507, in decorated
    openid_response, self.extension_responses))
  File "/var/www/get5-web/get5/__init__.py", line 124, in create_or_login
    g.user.steam_id, app.config['STEAM_API_KEY'])
  File "/var/www/get5-web/get5/steamid.py", line 104, in get_steam_userinfo
    rv = json.load(urllib2.urlopen(url))
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 403: Forbidden
[2018-04-25 11:52:58,372] {/var/www/get5-web/get5/__init__.py:155} ERROR - HTTP Error 403: Forbidden

**Comment by supaflybanzai** [comment]
ok now it works
i should write api WEB key not api gameserver key
